### ISSUE TITLE
Use of the global namespace

### ISSUE THREAD

**Issue by RachBLondon** [fourloops/CloudSound#29]
Lot's of global variables, not necessarily a problem at this stage but it's best practice to avoid using the global namespace as much as possible.

**Comment by otajor** [comment]
Yeah good point. So we should create the variables in the functions and pass them from one to the other as needed?

**Comment by RachBLondon** [comment]
Yes that is one solution, an easier way though might be to wrap the whole js file in a anonymous self invoking function ( a bit of a mouthful) Some more info can be found here: https://sarfraznawaz.wordpress.com/2012/01/26/javascript-self-invoking-functions/

**Comment by samhstn** [comment]
We'll look in to variables needing to be used between two js files without making them global, thanks for the info though
