### ISSUE TITLE
Refactor togglemap function in script.js

### ISSUE THREAD

**Issue by katbow** [fourloops/CloudSound#32]
Could use .toggleClass to switch between hiding and showing maps

**Comment by sohilpandya** [comment]
you might want to link to the actual code where they need to change this. makes it easier. https://github.com/fourloops/CloudSound/blob/master/script.js#L103-L118
 :smile:

**Comment by katbow** [comment]
Thanks @sohilpandya , I didn't actually know how to do that hah. Much better!
