### ISSUE TITLE
Why do you get all tracks if you only use the first?

### ISSUE THREAD

**Issue by eliasmalik** [fourloops/CloudSound#35]
You get all tracks [here](https://github.com/fourloops/CloudSound/blob/master/cloudsound.js#L22-L41) but only use the first element [here](https://github.com/fourloops/CloudSound/blob/master/cloudsound.js#L104)

**Comment by otajor** [comment]
We didn't have time to get a working randomiser up and running. We'll try to do it later after the code review.

Also, even without the randomiser, the user can click next to cycle through the whole list of songs.

**Comment by eliasmalik** [comment]
Fair enough.

**Comment by franzmoro** [comment]
the purpose is exactly to click through the next songs. Even with the randomizer, we would still collect all songs
